[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.17.0"

[[constraint]]
  name = "github.com/apex/gateway"
  version = "1.1.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
